NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
code="SHAMPOO"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/oil.jpeg"

[[CURRENCIES]]
code="PURIF"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/purif.jpeg"

[[CURRENCIES]]
code="REBAL"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/rebalan.jpeg"

[[CURRENCIES]]
code="SALI"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/sali.jpeg"

[[CURRENCIES]]
code="HAIR"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/hair.jpeg"

[[CURRENCIES]]
code="TREAT3D"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://curatori1.github.io/CUR/3d.jpeg"

[[CURRENCIES]]
code="OI"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_precision=2
image="https://cura
          

